language: node_js
node_js:
  - 0.6

before_install: 
  - "make install_chrome_travis"
  - "make install_xvfb_travis"
before_script: 
  - "make start_xvfb_forever"
  - "make start_server_forever" 

script: "make kernel_tests_travis"