language: node_js
node_js:
  - 0.6

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install chromium-browser"
  - "sudo apt-get install xvfb"

before_script:
  - "Xvfb :1 -screen 0 800x600x24&"
  - "make start_server_forever"

script: "make travis_tests"

branches:
  only:
    - master
